version: "3.8" # Especifica a versão da sintaxe do Compose

services: # A conjunto de contêineres que ira rodar
  #Serviço 1: WAF
  waf:
    build: ./waf
    ports:
      - "80:80" # A porta de entrada agora é a 80 (padrão web)
    depends_on:
      - app
    networks:
      - default

  # Serviço 2: Aplicativo Flask
  app:
    build: ./app # "Construa este serviço usando o Dockerfile da pasta ./app"
    environment:
      # "Injeta" os segredos do arquivo .env para o nosso app Python
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
    depends_on:
      - db # "Não inicia o 'app' até que o serviço 'db' esteja pronto"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - default
      - wazuh_net

  # Serviço 3: O Banco de Dados PostgreSQL
  db:
    image: postgres:15-alpine # "Usando imagem oficial do Postgres (versão 'alpine')"
    environment:
      # "Configura" o contêiner do Postgres usando os secrets
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Define o "volume" (armazenamento persistente)
volumes:
  postgres_data:

networks:
  default:
    driver: bridge

  wazuh_net:
    external: true
    name: single-node_default
